version: "3.8"

services:
  executor:
    image: ghcr.io/paradigmxyz/reth
    command:
      - node
      - -vvvv
      - --datadir=/execution-data
      - --chain=/el-cl-genesis-data/custom_config_data/genesis.json
      - --addr=${IP_ADDRESS}
      - --port=50403
      - --http
      - --http.port=8545
      - --http.addr=${IP_ADDRESS}
      - --http.corsdomain=*
      - --http.api=admin,net,eth,web3,debug,trace
      - --ws
      - --ws.addr=${IP_ADDRESS}
      - --ws.port=8546
      - --ws.api=net,eth
      - --ws.origins=*
      - --nat=extip:${IP_ADDRESS}
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/el-cl-genesis-data/jwt/jwtsecret
      - --authrpc.addr=${IP_ADDRESS}
      - --bootnodes=enode://de18715ae94d2545c70f396feadf3d88da1bb0ad1a845c2b1f6d98f1075ec4c05651f0fb4388f2c256731590636a799243b7d25839848add1efffd1eecf7edf2@88.99.94.109:50303
    volumes:
      - ./execution-data:/execution-data
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "10645:8545" 
      - "10646:8546" 
      - "10651:8551" 
      - "11101:11101" 
      - "50403:50403"
    restart: unless-stopped

  beacon:
    image: sigp/lighthouse:v4.5.0
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/consensus-data
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --disable-enr-auto-update
      - --enr-address=${IP_ADDRESS}
      - --enr-udp-port=11100
      - --enr-tcp-port=11100
      - --listen-address=0.0.0.0
      - --port=11100
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --http-allow-sync-stalled
      - --slots-per-restore-point=32
      - --disable-packet-filter
      - --execution-endpoints=http://executor:8551
      - --jwt-secrets=/el-cl-genesis-data/jwt/jwtsecret
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --subscribe-all-subnets
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --trusted-peers=16Uiu2HAkxAjbNY3VD7fS4w3f6pfk2dnKiAPr6tDQtd2vvUmEX54L
      - --boot-nodes=enr:-MS4QDAfdwdv39sNGp4RhwyabW-n-bNHMFgjgrPsImZKfibtQAGKg85CqmVKg_jvA7r_7C75tu7lv7CDASsQwboc9QYBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpAjvkwgQAAAOP__________gmlkgnY0gmlwhFhjXm2EcXVpY4Iq-YlzZWNwMjU2azGhAii_bzHcO9ydFheDTk140o6hvL0tnMTd89PPGnINuuORiHN5bmNuZXRzAIN0Y3CCKviDdWRwgir4
      - --checkpoint-sync-url=http://88.99.94.109:9781
      - --disable-optimistic-finalized-sync
      - --disable-backfill-rate-limiting
      - --genesis-backfill
      - --reconstruct-historic-states
      - --reset-payload-statuses
    volumes:
      - ./consensus-data:/consensus-data 
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "11100:11100/udp"
      - "11100:11100/tcp" 
      - "4300:4000"
      - "7154:5054"
    depends_on:
      - executor
    restart: unless-stopped

  # lighthouse-validator:
  #   image: sigp/lighthouse:v4.5.0
  #   command:
  #     - lighthouse
  #     - validator_client
  #     - --debug-level=info
  #     - --testnet-dir=/el-cl-genesis-data/custom_config_data
  #     - --validators-dir=/validator-keys/node-0-keystores/keys
  #     - --secrets-dir=/validator-keys/node-0-keystores/secrets
  #     - --init-slashing-protection
  #     - --http
  #     - --unencrypted-http-transport
  #     - --http-address=0.0.0.0
  #     - --http-port=5042
  #     - --beacon-nodes=http://lighthouse-beacon:4000
  #     - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
  #     - --metrics
  #     - --metrics-address=0.0.0.0
  #     - --metrics-allow-origin=*
  #     - --metrics-port=5064
  #   volumes:
  #     - ./el-cl-genesis-data:/el-cl-genesis-data
  #     - ./validator-keys:/validator-keys
  #   ports:
  #     - "7042:5042"
  #     - "7064:5064"
  #   depends_on:
  #     - lighthouse-beacon
  #   restart: unless-stopped
